param(
  [Parameter(Mandatory = $true)]
  [string]$RepoRoot,
  [string]$ConfigPath = $null
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Get-FullPath {
  param([Parameter(Mandatory = $true)][string]$Path)
  return [System.IO.Path]::GetFullPath($Path)
}

function Resolve-ConfigPath {
  param(
    [Parameter(Mandatory = $true)]
    [string]$Root,
    [string]$RequestedPath
  )

  if ($RequestedPath) {
    return (Get-FullPath $RequestedPath)
  }

  $localConfig = Join-Path $Root "setup.json"
  if (Test-Path -LiteralPath $localConfig) {
    return (Get-FullPath $localConfig)
  }

  return (Get-FullPath (Join-Path $Root "setup.example.json"))
}

function Read-JsonFile {
  param([Parameter(Mandatory = $true)][string]$Path)
  return (Get-Content -Raw -LiteralPath $Path | ConvertFrom-Json)
}

function Get-ClientConfig {
  param(
    [Parameter(Mandatory = $true)]
    [object]$Config,
    [Parameter(Mandatory = $true)]
    [string]$ClientName
  )

  $property = $Config.clients.PSObject.Properties[$ClientName]
  if ($property) {
    return $property.Value
  }

  return $null
}

function Get-ObjectProperty {
  param(
    [object]$Object,
    [Parameter(Mandatory = $true)]
    [string]$Name
  )

  if (-not $Object) {
    return $null
  }

  $property = $Object.PSObject.Properties[$Name]
  if ($property) {
    return $property.Value
  }

  return $null
}

function Write-Utf8NoBom {
  param(
    [Parameter(Mandatory = $true)]
    [string]$Path,
    [Parameter(Mandatory = $true)]
    [string]$Content
  )

  $parent = Split-Path -Parent $Path
  if ($parent) {
    New-Item -ItemType Directory -Force -Path $parent | Out-Null
  }

  [System.IO.File]::WriteAllText($Path, $Content, [System.Text.UTF8Encoding]::new($false))
}

function Join-Content {
  param(
    [string[]]$Paths
  )

  $parts = foreach ($path in $Paths) {
    Get-Content -Raw -LiteralPath $path
  }

  return ($parts -join "`r`n")
}

function Get-RulePaths {
  param(
    [Parameter(Mandatory = $true)]
    [string]$RulesDir,
    [string[]]$PreferredOrder = @()
  )

  if (-not (Test-Path -LiteralPath $RulesDir)) {
    return @()
  }

  $orderedPaths = foreach ($ruleFile in $PreferredOrder) {
    $path = Join-Path $RulesDir $ruleFile
    if (Test-Path -LiteralPath $path) {
      $path
    }
  }

  $extraPaths = Get-ChildItem -LiteralPath $RulesDir -Filter "*.md" -File |
    Where-Object { $PreferredOrder -notcontains $_.Name } |
    Sort-Object Name |
    ForEach-Object { $_.FullName }

  $paths = @($orderedPaths)
  if ($extraPaths) {
    $paths += @($extraPaths)
  }

  return $paths
}

function Get-PromptFileName {
  param([Parameter(Mandatory = $true)][string]$ClientName)

  if ($ClientName -eq "claude") {
    return "CLAUDE.md"
  }

  return "AGENTS.md"
}

$repoRootFull = Get-FullPath $RepoRoot
$configPathFull = Resolve-ConfigPath -Root $repoRootFull -RequestedPath $ConfigPath
if (-not (Test-Path -LiteralPath $configPathFull)) {
  throw "Missing setup config: $configPathFull"
}

$config = Read-JsonFile $configPathFull
$rulesDir = Join-Path $repoRootFull "shared/rules"
$clientRoot = Join-Path $repoRootFull "clients"
$generatedRoot = Join-Path $repoRootFull "generated"

$ruleOrder = @("core.md", "workflow.md", "frontend-design.md")
$sharedRulePaths = Get-RulePaths -RulesDir $rulesDir -PreferredOrder $ruleOrder
foreach ($ruleFile in $ruleOrder) {
  $path = Join-Path $rulesDir $ruleFile
  if (-not (Test-Path -LiteralPath $path)) {
    throw "Missing shared rule file: $path"
  }
}

$clientDirs = Get-ChildItem -LiteralPath $clientRoot -Directory | Sort-Object Name

foreach ($clientDir in $clientDirs) {
  $clientName = $clientDir.Name
  $promptFileName = Get-PromptFileName $clientName
  $clientRulesDir = Join-Path $clientDir.FullName "rules"
  if (-not (Test-Path -LiteralPath $clientRulesDir)) {
    throw "Missing client rules directory: $clientRulesDir"
  }

  $clientRulePaths = Get-RulePaths -RulesDir $clientRulesDir
  $generatedNotice = @(
    "<!-- Generated by agent-config. Do not edit directly. -->",
    "",
    "# $clientName Agent Config"
  ) -join "`r`n"
  $contentParts = @($generatedNotice, (Join-Content ($sharedRulePaths + $clientRulePaths)))
  $content = $contentParts -join "`r`n`r`n"
  $generatedPath = Join-Path (Join-Path $generatedRoot $clientName) $promptFileName
  Write-Utf8NoBom -Path $generatedPath -Content $content

  $clientConfig = Get-ClientConfig -Config $config -ClientName $clientName
  $promptTargetValue = Get-ObjectProperty -Object $clientConfig -Name "promptTarget"
  if ($promptTargetValue) {
    $promptTarget = Get-FullPath $promptTargetValue
    Write-Utf8NoBom -Path $promptTarget -Content $content
    Write-Host "Generated and deployed $clientName prompt: $promptTarget"
  } else {
    Write-Host "Generated $clientName prompt: $generatedPath"
  }
}
