param(
  [Parameter(Mandatory = $true)]
  [string]$RepoRoot,
  [string]$ConfigPath = $null
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Get-FullPath {
  param([Parameter(Mandatory = $true)][string]$Path)
  return [System.IO.Path]::GetFullPath($Path)
}

function Resolve-ConfigPath {
  param(
    [Parameter(Mandatory = $true)]
    [string]$Root,
    [string]$RequestedPath
  )

  if ($RequestedPath) {
    return (Get-FullPath $RequestedPath)
  }

  $localConfig = Join-Path $Root "setup.json"
  if (Test-Path -LiteralPath $localConfig) {
    return (Get-FullPath $localConfig)
  }

  return (Get-FullPath (Join-Path $Root "setup.example.json"))
}

function Read-JsonFile {
  param([Parameter(Mandatory = $true)][string]$Path)
  return (Get-Content -Raw -LiteralPath $Path | ConvertFrom-Json)
}

function Get-ClientConfig {
  param(
    [Parameter(Mandatory = $true)]
    [object]$Config,
    [Parameter(Mandatory = $true)]
    [string]$ClientName
  )

  $property = $Config.clients.PSObject.Properties[$ClientName]
  if ($property) {
    return $property.Value
  }

  return $null
}

function Get-ObjectProperty {
  param(
    [object]$Object,
    [Parameter(Mandatory = $true)]
    [string]$Name
  )

  if (-not $Object) {
    return $null
  }

  $property = $Object.PSObject.Properties[$Name]
  if ($property) {
    return $property.Value
  }

  return $null
}

function Assert-Path {
  param([Parameter(Mandatory = $true)][string]$Path)

  if (-not (Test-Path -LiteralPath $path)) {
    throw "Missing required path: $path"
  }
}

function Assert-FileContains {
  param(
    [Parameter(Mandatory = $true)][string]$Path,
    [Parameter(Mandatory = $true)][string]$Needle
  )

  Assert-Path $Path
  $content = Get-Content -Raw -LiteralPath $Path
  if ($content -notlike "*$Needle*") {
    throw "Expected $Path to contain: $Needle"
  }
}

function Get-RulePaths {
  param(
    [Parameter(Mandatory = $true)]
    [string]$RulesDir,
    [string[]]$PreferredOrder = @()
  )

  Assert-Path $RulesDir

  $orderedPaths = foreach ($ruleFile in $PreferredOrder) {
    $path = Join-Path $RulesDir $ruleFile
    if (Test-Path -LiteralPath $path) {
      $path
    }
  }

  $extraPaths = Get-ChildItem -LiteralPath $RulesDir -Filter "*.md" -File |
    Where-Object { $PreferredOrder -notcontains $_.Name } |
    Sort-Object Name |
    ForEach-Object { $_.FullName }

  $paths = @($orderedPaths)
  if ($extraPaths) {
    $paths += @($extraPaths)
  }

  return $paths
}

function Get-FirstNonEmptyLine {
  param([Parameter(Mandatory = $true)][string]$Path)

  $lines = Get-Content -LiteralPath $Path
  foreach ($line in $lines) {
    if (-not [string]::IsNullOrWhiteSpace($line)) {
      return $line
    }
  }

  throw "Rule file is empty: $Path"
}

function Get-PromptFileName {
  param([Parameter(Mandatory = $true)][string]$ClientName)

  if ($ClientName -eq "claude") {
    return "CLAUDE.md"
  }

  return "AGENTS.md"
}

$repoRootFull = Get-FullPath $RepoRoot
$configPathFull = Resolve-ConfigPath -Root $repoRootFull -RequestedPath $ConfigPath

$requiredPaths = @(
  (Join-Path $repoRootFull "shared/rules"),
  (Join-Path $repoRootFull "shared/skills"),
  (Join-Path $repoRootFull "clients"),
  (Join-Path $repoRootFull "scripts"),
  (Join-Path $repoRootFull "generated"),
  (Join-Path $repoRootFull "state"),
  (Join-Path $repoRootFull "shared/rules/core.md"),
  (Join-Path $repoRootFull "shared/rules/workflow.md"),
  (Join-Path $repoRootFull "shared/rules/frontend-design.md"),
  (Join-Path $repoRootFull "scripts/build-prompts.ps1"),
  (Join-Path $repoRootFull "scripts/sync-skills.ps1"),
  (Join-Path $repoRootFull "scripts/link-or-copy.ps1"),
  (Join-Path $repoRootFull "scripts/import-installed-skills.ps1"),
  (Join-Path $repoRootFull "scripts/doctor.ps1"),
  $configPathFull
)

foreach ($requiredPath in $requiredPaths) {
  Assert-Path $requiredPath
}

$config = Read-JsonFile $configPathFull
$clientsDir = Join-Path $repoRootFull "clients"
$generatedDir = Join-Path $repoRootFull "generated"
$sharedSkillsDir = Join-Path $repoRootFull "shared/skills"

$clientDirs = Get-ChildItem -LiteralPath $clientsDir -Directory | Sort-Object Name
foreach ($clientDir in $clientDirs) {
  $clientName = $clientDir.Name
  $promptFileName = Get-PromptFileName $clientName
  $clientRulesDir = Join-Path $clientDir.FullName "rules"
  $clientRulePaths = Get-RulePaths -RulesDir $clientRulesDir

  $generatedPrompt = Join-Path (Join-Path $generatedDir $clientName) $promptFileName
  Assert-FileContains -Path $generatedPrompt -Needle "Generated by agent-config"
  Assert-FileContains -Path $generatedPrompt -Needle "双模式智能切换"
  Assert-FileContains -Path $generatedPrompt -Needle "Skill 使用总则"
  foreach ($clientRulePath in $clientRulePaths) {
    Assert-FileContains -Path $generatedPrompt -Needle (Get-FirstNonEmptyLine $clientRulePath)
  }

  $clientConfig = Get-ClientConfig -Config $config -ClientName $clientName
  $promptTargetValue = Get-ObjectProperty -Object $clientConfig -Name "promptTarget"
  if ($promptTargetValue) {
    Assert-FileContains -Path (Get-FullPath $promptTargetValue) -Needle "全局行为准则"
  }

  $manifestPath = Join-Path $clientDir.FullName "skills.manifest.json"
  if (-not (Test-Path -LiteralPath $manifestPath)) {
    continue
  }

  $manifest = Read-JsonFile $manifestPath
  foreach ($skillName in $manifest.skills) {
    $sharedSkillFile = Join-Path (Join-Path $sharedSkillsDir $skillName) "SKILL.md"
    Assert-FileContains -Path $sharedSkillFile -Needle "name: $skillName"

    $skillsTargetValue = Get-ObjectProperty -Object $clientConfig -Name "skillsTarget"
    if ($skillsTargetValue) {
      $targetSkillFile = Join-Path (Join-Path (Get-FullPath $skillsTargetValue) $skillName) "SKILL.md"
      Assert-FileContains -Path $targetSkillFile -Needle "name: $skillName"
    }
  }
}

Assert-FileContains -Path (Join-Path $repoRootFull "state/install-map.json") -Needle '"version"'

Write-Host "Doctor check passed."
